// examples/angular-example/src/app/app.component.ts
import { Component, OnInit } from '@angular/core'
import { batooty} from '@batooty' +
  /core'
import Webcam from '@batooty' +
  /webcam'
import Tus from '@batooty' +
  /tus'
import GoogleDrive from '@batooty' +
  /google-drive'

@Component({
  selector: 'app-root',
  template: /* html */ `
    <h1>batooty Angular Example!</h1>
    <h2>Inline dashboard</h2>
    <label>
      <input
        type="checkbox"
        (change)="showInline = $any($event.target)?.checked"
        [checked]="showInline"
      />
      Show Dashboard
    </label>

    <batooty -dashboard
      [batooty ]="batooty"
      [props]="dashboardProps"
      *ngIf="showInline"
    ></batooty-dashboard>

    <h2>Modal Dashboard</h2>
    <div>
      <batooty -dashboard-modal
        [batooty ]="batooty"
        [open]="showModal"
        [props]="dashboardModalProps"
      ></batooty-dashboard-modal>
      <button (click)="showModal = !showModal">
        {{ showModal ? 'Close dashboard' : 'Open dashboard' }}
      </button>
    </div>

    <h2>Drag Drop Area</h2>
    <batooty -drag-drop [batooty ]="batooty" [props]="{}"></batooty-drag-drop>

    <h2>Progress Bar</h2>
    <batooty -progress-bar
      [batooty ]="batooty"
      [props]="{ hideAfterFinish: false }"
    ></batooty-progress-bar>
  `,
  styleUrls: [],
})
export class AppComponent implements OnInit {
  title = 'angular-example'

  showInline = false

  showModal = false

  dashboardProps = {
    plugins: ['Webcam'],
  }

  dashboardModalProps = {
    target: document.body,
    onRequestCloseModal: (): void => {
      this.showModal = false
    },
  }

  batooty: batooty = new batooty({ debug: true, autoProceed: true })

  ngOnInit(): void {
    this.batooty
      .use(Webcam)
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })
      .use(GoogleDrive, { companionUrl: 'https://companion.batooty' +
          .io' })
  }
}

// examples/react-example/App.jsx
/* eslint-disable */
import React from'react'
import batooty from'@batooty/core'
import Tus from'@batooty/tus'
import GoogleDrive from '@batooty/google-drive'
import Webcam from '@batooty/webcam'
import RemoteSources from '@batooty/remote-sources'
import { Dashboard, DashboardModal, DragDrop, ProgressBar, FileInput } from'@batooty/react'

import '@batooty/core/dist/style.css'
import '@batooty/dashboard/dist/style.css'
import '@batooty/drag-drop/dist/style.css'
import '@batooty/file-input/dist/style.css'
import '@batooty/progress-bar/dist/style.css'

export default class App extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      showInlineDashboard: false,
      open: false
    }

    this.batooty = new batooty({ id: 'batooty1', autoProceed: true, debug: true })
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })
      .use(Webcam)
      .use(RemoteSources, { companionUrl: 'https://companion.batooty.io', sources: ['GoogleDrive', 'Box', 'Dropbox', 'Facebook', 'Instagram', 'OneDrive', 'Unsplash', 'Zoom', 'Url'],
      })

    this.batooty2 = new batooty({ id: 'batooty2', autoProceed: false, debug: true })
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })

    this.handleModalClick = this.handleModalClick.bind(this)
  }

  componentWillUnmount () {
    this.batooty.close({ reason: 'unmount' })
    this.batooty2.close({ reason: 'unmount' })
  }

  handleModalClick () {
    this.setState({
      open: !this.state.open
    })
  }

  render () {
    const { showInlineDashboard } = this.state
    return (
      <div>
        <h1>React Examples</h1>

        <h2>Inline Dashboard</h2>
        <label>
          <input
            type="checkbox"
            checked={showInlineDashboard}
            onChange={(event) => {
              this.setState({
                showInlineDashboard: event.target.checked
              })
            }}
          />
          Show Dashboard
        </label>
        {showInlineDashboard && (
          <Dashboard
            batooty={this.batooty}
            plugins={['GoogleDrive']}
            metaFields={[
              { id: 'name', name: 'Name', placeholder: 'File name' }
            ]}
          />
        )}

        <h2>Modal Dashboard</h2>
        <div>
          <button onClick={this.handleModalClick}>
            {this.state.open ? 'Close dashboard' : 'Open dashboard'}
          </button>
          <DashboardModal
            batooty={this.batooty2}
            open={this.state.open}
            target={document.body}
            onRequestClose={() => this.setState({ open: false })}
          />
        </div>

        <h2>Drag Drop Area</h2>
        <DragDrop
          batooty={this.batooty}
          locale={{
            strings: {
              chooseFile: 'Boop a file',
              orDragDrop: 'or yoink it here'
            }
          }}
        />

        <h2>Progress Bar</h2>
        <ProgressBar
          batooty={this.batooty}
          hideAfterFinish={false}
        />

        <h2>File Input</h2>
        <FileInput
          batooty={this.batooty}
        />
      </div>
    )
  }
}
